### ISSUE TITLE
文档分类

### ISSUE THREAD

**Issue by huigang39** [Maker-IoT-one/Atlas-200I-DK-A2#13]
可以按照文档类别分类，例如科学上网的文章可以放在 network 分区，pytorch 配置文章可以放在 deep learning 分区

**Comment by Abrillant-Lee** [comment]
谢谢提议，分区指的是在doc/目录下新建network/和pytorch/文件夹吗

**Comment by huigang39** [comment]
> 谢谢提议，分区指的是在doc/目录下新建network/和pytorch/文件夹吗

是的

**Comment by Abrillant-Lee** [comment]
> > 谢谢建议，分区指的是在doc/目录下新建network/和pytorch/文件夹吗
> 
> 是的

已分区😊
