### ISSUE TITLE
昇腾拒绝连接

### ISSUE THREAD

**Issue by ryanzhang66** [Maker-IoT-one/Atlas-200I-DK-A2#4]
- 我在使用192.168.137.2登陆时，连接超时
![image](https://github.com/Abrillant-Lee/Atlas-200I-DK-A2/assets/112852515/aaa9fda8-c931-4f04-83f3-7b7e8a41d8e3)
- 但是可以ping通
![image](https://github.com/Abrillant-Lee/Atlas-200I-DK-A2/assets/112852515/0bf4c3ed-dc6c-4d4c-832f-7a4065e47212)
- 我通过重新配置网络解决了，是否还有其他办法？

**Comment by Abrillant-Lee** [comment]
我使用的时候也遇到过这个问题☹️，后来解决办法是：重新插拔网线😶，如果你使用的是type-c，也不妨试试重新插拔，万一成功了呢😁

**Comment by huigang39** [comment]
你图上 ping 的不是你本机的IP？`192.168.137.1` 不是你自己本机的网卡 ip？
