### ISSUE TITLE
使用网卡不能访问外网

### ISSUE THREAD

**Issue by ryanzhang66** [Maker-IoT-one/Atlas-200I-DK-A2#8]
- 使用网卡跟着原来的配置代理步骤不能访问外网，他会给我错误的本机IP地址
![image](https://github.com/Abrillant-Lee/Atlas-200I-DK-A2/assets/112852515/c77671ab-739e-43ff-b7b7-615f73e7257f)
- 我把IP地址更换为`127.0.0.1`
![image](https://github.com/Abrillant-Lee/Atlas-200I-DK-A2/assets/112852515/e5fb6ba2-70f9-4a27-811a-86c67bd6d0e7)
- 可以正常访问
![image](https://github.com/Abrillant-Lee/Atlas-200I-DK-A2/assets/112852515/b182c534-941e-4b05-b2ef-b2ac9fa49919)

**Comment by Abrillant-Lee** [comment]
这个问题可能是由于你的代理服务器clash只监听在本地（localhost，即127.0.0.1）上，而不是在你的默认路由的IP地址上。当你尝试使用默认路由的IP地址作为代理服务器的地址时，你的请求可能无法到达代理服务器，因为代理服务器并没有在那个地址上监听。

如果你的代理服务器只在本地监听，那么你应该使用127.0.0.1作为代理服务器的地址。如果你想让你的代理服务器在其他地址上监听，你需要在启动代理服务器时指定正确的监听地址。
